name: Build Android On Ubuntu

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run unit test
        run: |
          cd mobile_ui
          yarn install
          yarn test

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate debug apk file
        run: |
          cd mobile_ui
          yarn install
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: mobile_ui/android/app/build/outputs/apk/debug/
