name: api collections with postman

on:
  push:
    branches:
      - server

# three job definition
jobs:
  API-collection-testing-job: # health check job for testing and code formatting check
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
        with:
          ref: server
      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for results
        run: |
          cd Aquality2
          mkdir -p testResults

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          cd Aquality2
          newman run ./tests/CCCMI .postman_collection.json.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
