name: Django CI Workflow

on:
  push:
    branches:
      - master

# three job definition
jobs:
  secret:
    runs-on: ubuntu-latest # os for running the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: server
      - name: print secrets
        run: |
          cd Aquality2
          touch .env
          echo $DEV_ENV_FILE | tr ' ' '\n' >> .env
          cat .env
        env:
          DEV_ENV_FILE: ${{ secrets.SERVER_ENV }}
        shell: bash
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV_ENV_FILE
          path: Aquality2/.env
# update env
