name: Django CI Workflow

on:
  push:
    branches:
      - server

# three job definition
jobs:
  secret:
    runs-on: ubuntu-latest # os for running the jobsdsd
    steps:
      - uses: actions/checkout@v2
        with:
          ref: server
      - name: print secrets
        with: # Set the secret as an input
          DEV_ENV_FILE: ${{ secrets.SERVER_ENV }}
        run: |
          cd Aquality2
          touch .env
          echo $DEV_ENV_FILE >> .env
          cat .env
        shell: bash
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV_ENV_FILE
          path: Aquality2/.env
